Algoritmo "semnome"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Antonio Carlos Nicolodi 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 05/09/2025
Var
// Seção de Declarações das variáveis 
valor, acrescimo:real

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
  Escreval("Digite o valor do Produto")
  leia(valor)
  
  acrescimo <- valor + (valor*0.25)
  
  escreval("O novo valor é:" , acrescimo)
  



Fimalgoritmo