Algoritmo "semnome"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Antonio Carlos Nicolodi 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 05/09/2025
Var
// Seção de Declarações das variáveis 
nome:caractere
anonascimento, idade:inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
   escreval("Digite seu nome")
   leia(nome)
   escreval("Digite seu ano de nascimento")
   leia(anonascimento)
   
   
   idade <- 2025 - anonascimento
   
    escreval("dados do usuario!!!!")
   escreval("Seu nome é ", nome)
   escreval("Sua idade é ", idade)

Fimalgoritmo