Algoritmo "semnome"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Antonio Carlos Nicolodi 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 05/09/2025
Var
// Seção de Declarações das variáveis 
 valor, antecessor:real

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
   escreval("digite o valor")
   leia(valor)
   antecessor <- (valor - 1)
   escreval("o valor é: ", antecessor)
   

Fimalgoritmo